const Head = () => {
  return (
    <>
      <title>Pacio - Creative web developer</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/assets/logo-circle.png' />
      <script src='/assets/js/hero.js' defer async />
    </>
  );
};

export default Head;
